### ISSUE TITLE
Correios fora do ar

### ISSUE THREAD

**Issue by frankdors** [prodis/correios-sro-xml#4]
Alguém sabe dizer se nessa semana os Correios estão fora do ar para usar rastreamento ou se mudou algo que deverá ser ajustado?

**Comment by prodis** [comment]
O serviço está fora, redirecionando para a página dos Correios.

Assim que tiver alguma novidade, eu aviso.

**Comment by vinidade** [comment]
Olá,
O problema então é no webservice dos Correios?
Será que tiraram do ar em definitivo ou é um problema mesmo?

**Comment by frankdors** [comment]
@vinidade @prodis 
Sim, saiu do Ar...

Aqui tem mais informações para nova integração:
https://github.com/pedro-teixeira/correios/pull/139#issuecomment-226487209
https://github.com/ivanwhm/correios/issues/5

**Comment by prodis** [comment]
Obrigado, @frankdors.

Planejo fazer a alteração amanhã.

**Comment by prodis** [comment]
Solved in 0.4.0 version.

Thanks, @lemanchester.
